-- MySQL Script generated by MySQL Workbench
-- Wed Apr 22 01:13:12 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema cine
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema cineflow
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cineflow
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cineflow` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
-- -----------------------------------------------------
-- Schema new_schema
-- -----------------------------------------------------
USE `cineflow` ;

-- -----------------------------------------------------
-- Table `cineflow`.`PAGO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cineflow`.`PAGO` (
  `idPago` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `monto` DECIMAL(10,2) NOT NULL,
  `fecha` DATETIME NOT NULL,
  `estado` VARCHAR(30) NOT NULL,
  `metodo` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`idPago`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cineflow`.`PELICULA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cineflow`.`PELICULA` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(180) NOT NULL,
  `duracion` INT NOT NULL,
  `sinopsis` TEXT NULL DEFAULT NULL,
  `edad_restriccion` VARCHAR(10) NULL DEFAULT NULL,
  `genero` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cineflow`.`USUARIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cineflow`.`USUARIO` (
  `idUsuario` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(120) NOT NULL,
  `contrasenia` VARCHAR(255) NOT NULL,
  `nombre` VARCHAR(80) NOT NULL,
  `apellidos` VARCHAR(120) NOT NULL,
  `telefono` VARCHAR(20) NULL DEFAULT NULL,
  `fechaNacimiento` DATE NULL DEFAULT NULL,
  `fechaRegistro` DATETIME NOT NULL,
  PRIMARY KEY (`idUsuario`),
  UNIQUE INDEX `email` (`email` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cineflow`.`RESERVA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cineflow`.`RESERVA` (
  `idReserva` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `fechaReserva` DATETIME NOT NULL,
  `fechaExpiracion` DATETIME NULL DEFAULT NULL,
  `estado` VARCHAR(30) NOT NULL,
  `totalFinal` DECIMAL(10,2) NOT NULL DEFAULT '0.00',
  `fid_usuario` INT UNSIGNED NULL DEFAULT NULL,
  `fid_pago` INT UNSIGNED NULL DEFAULT NULL,
  PRIMARY KEY (`idReserva`),
  INDEX `fk_reserva_usuario` (`fid_usuario` ASC) VISIBLE,
  INDEX `fk_reserva_pago` (`fid_pago` ASC) VISIBLE,
  CONSTRAINT `fk_reserva_pago`
    FOREIGN KEY (`fid_pago`)
    REFERENCES `cineflow`.`PAGO` (`idPago`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_reserva_usuario`
    FOREIGN KEY (`fid_usuario`)
    REFERENCES `cineflow`.`USUARIO` (`idUsuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cineflow`.`ESTADO_ASIENTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cineflow`.`ESTADO_ASIENTO` (
  `id_estado_asiento` TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id_estado_asiento`),
  UNIQUE INDEX `nombre` (`nombre` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cineflow`.`FORMATO_PROYECCION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cineflow`.`FORMATO_PROYECCION` (
  `id_formato_proyeccion` TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`id_formato_proyeccion`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cineflow`.`CINE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cineflow`.`CINE` (
  `id_cine` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(120) NOT NULL,
  `ubicacion` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id_cine`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cineflow`.`SALA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cineflow`.`SALA` (
  `id_sala` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `numero` INT NOT NULL,
  `capacidad` INT NOT NULL,
  `id_cine` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_sala`),
  UNIQUE INDEX `uq_sala_numero_cine` (`id_cine` ASC, `numero` ASC) VISIBLE,
  CONSTRAINT `fk_sala_cine`
    FOREIGN KEY (`id_cine`)
    REFERENCES `cineflow`.`CINE` (`id_cine`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cineflow`.`FUNCION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cineflow`.`FUNCION` (
  `id_funcion` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `fecha_hora` DATETIME NOT NULL,
  `precio_base` DECIMAL(10,2) NOT NULL,
  `id_pelicula` INT UNSIGNED NOT NULL,
  `id_sala` INT UNSIGNED NOT NULL,
  `id_formato` TINYINT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_funcion`),
  INDEX `fk_funcion_pelicula` (`id_pelicula` ASC) VISIBLE,
  INDEX `fk_funcion_sala` (`id_sala` ASC) VISIBLE,
  INDEX `fk_funcion_formato` (`id_formato` ASC) VISIBLE,
  CONSTRAINT `fk_funcion_formato`
    FOREIGN KEY (`id_formato`)
    REFERENCES `cineflow`.`FORMATO_PROYECCION` (`id_formato_proyeccion`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_funcion_pelicula`
    FOREIGN KEY (`id_pelicula`)
    REFERENCES `cineflow`.`PELICULA` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_funcion_sala`
    FOREIGN KEY (`id_sala`)
    REFERENCES `cineflow`.`SALA` (`id_sala`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cineflow`.`asiento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cineflow`.`asiento` (
  `id_asiento` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `fila` CHAR(1) NOT NULL,
  `numero` INT NOT NULL,
  `id_estado_asiento` TINYINT UNSIGNED NOT NULL,
  `id_funcion` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_asiento`),
  UNIQUE INDEX `uq_asiento_funcion` (`id_funcion` ASC, `fila` ASC, `numero` ASC) VISIBLE,
  INDEX `fk_asiento_estado` (`id_estado_asiento` ASC) VISIBLE,
  CONSTRAINT `fk_asiento_estado`
    FOREIGN KEY (`id_estado_asiento`)
    REFERENCES `cineflow`.`ESTADO_ASIENTO` (`id_estado_asiento`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_asiento_funcion`
    FOREIGN KEY (`id_funcion`)
    REFERENCES `cineflow`.`FUNCION` (`id_funcion`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cineflow`.`CARTELERA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cineflow`.`CARTELERA` (
  `id_cartelera` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(120) NULL DEFAULT NULL,
  `id_cine` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_cartelera`),
  INDEX `fk_cartelera_cine` (`id_cine` ASC) VISIBLE,
  CONSTRAINT `fk_cartelera_cine`
    FOREIGN KEY (`id_cine`)
    REFERENCES `cineflow`.`CINE` (`id_cine`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cineflow`.`CARTELERA_PELICULA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cineflow`.`CARTELERA_PELICULA` (
  `id_cartelera` INT UNSIGNED NOT NULL,
  `id_pelicula` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_cartelera`, `id_pelicula`),
  INDEX `fk_cartelera_pelicula_pelicula` (`id_pelicula` ASC) VISIBLE,
  CONSTRAINT `fk_cartelera_pelicula_cartelera`
    FOREIGN KEY (`id_cartelera`)
    REFERENCES `cineflow`.`CARTELERA` (`id_cartelera`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_cartelera_pelicula_pelicula`
    FOREIGN KEY (`id_pelicula`)
    REFERENCES `cineflow`.`PELICULA` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cineflow`.`COMPROBANTE_COMPRA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cineflow`.`COMPROBANTE_COMPRA` (
  `id_comprobante` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `codigo_qr` VARCHAR(255) NULL DEFAULT NULL,
  `monto_total` DECIMAL(10,2) NOT NULL,
  `id_reserva` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_comprobante`),
  INDEX `fk_comprobante_reserva` (`id_reserva` ASC) VISIBLE,
  CONSTRAINT `fk_comprobante_reserva`
    FOREIGN KEY (`id_reserva`)
    REFERENCES `cineflow`.`RESERVA` (`idReserva`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cineflow`.`inventario_cine`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cineflow`.`inventario_cine` (
  `id_inventario` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `stock_actual` INT NOT NULL,
  `stock_minimo` INT NOT NULL,
  `ultima_reposicion` DATETIME NULL DEFAULT NULL,
  `id_cine` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_inventario`),
  INDEX `fk_inventario_cine` (`id_cine` ASC) VISIBLE,
  CONSTRAINT `fk_inventario_cine`
    FOREIGN KEY (`id_cine`)
    REFERENCES `cineflow`.`CINE` (`id_cine`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cineflow`.`CONFITERIA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cineflow`.`CONFITERIA` (
  `id_item` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(30) NOT NULL,
  `nombre` VARCHAR(120) NOT NULL,
  `cantidad` INT NOT NULL,
  `precio_unitario` DECIMAL(10,2) NOT NULL,
  `id_inventario` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_item`),
  INDEX `fk_confiteria_inventario` (`id_inventario` ASC) VISIBLE,
  CONSTRAINT `fk_confiteria_inventario`
    FOREIGN KEY (`id_inventario`)
    REFERENCES `cineflow`.`inventario_cine` (`id_inventario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cineflow`.`entrada`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cineflow`.`entrada` (
  `id_entrada` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(20) NOT NULL,
  `precio_base` DECIMAL(10,2) NOT NULL,
  `id_reserva` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_entrada`),
  INDEX `fk_entrada_reserva` (`id_reserva` ASC) VISIBLE,
  CONSTRAINT `fk_entrada_reserva`
    FOREIGN KEY (`id_reserva`)
    REFERENCES `cineflow`.`RESERVA` (`idReserva`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cineflow`.`ESTADO_PAGO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cineflow`.`ESTADO_PAGO` (
  `id_estado_pago` TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id_estado_pago`),
  UNIQUE INDEX `nombre` (`nombre` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cineflow`.`estado_reserva`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cineflow`.`estado_reserva` (
  `id_estado_reserva` TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id_estado_reserva`),
  UNIQUE INDEX `nombre` (`nombre` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cineflow`.`METODO_PAGO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cineflow`.`METODO_PAGO` (
  `id_metodo_pago` TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`id_metodo_pago`),
  UNIQUE INDEX `nombre` (`nombre` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cineflow`.`RESERV`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cineflow`.`reserva_asiento` (
  `id_reserva` INT UNSIGNED NOT NULL,
  `id_asiento` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_reserva`, `id_asiento`),
  INDEX `fk_reserva_asiento_asiento` (`id_asiento` ASC) VISIBLE,
  CONSTRAINT `fk_reserva_asiento_asiento`
    FOREIGN KEY (`id_asiento`)
    REFERENCES `cineflow`.`asiento` (`id_asiento`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_reserva_asiento_reserva`
    FOREIGN KEY (`id_reserva`)
    REFERENCES `cineflow`.`RESERVA` (`idReserva`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cineflow`.`RESERVA_CONFITERIA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cineflow`.`RESERVA_CONFITERIA` (
  `id_reserva` INT UNSIGNED NOT NULL,
  `id_item` INT UNSIGNED NOT NULL,
  `cantidad` INT NOT NULL DEFAULT '1',
  `precio_unitario` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`id_reserva`, `id_item`),
  INDEX `fk_reserva_confiteria_item` (`id_item` ASC) VISIBLE,
  CONSTRAINT `fk_reserva_confiteria_item`
    FOREIGN KEY (`id_item`)
    REFERENCES `cineflow`.`CONFITERIA` (`id_item`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_reserva_confiteria_reserva`
    FOREIGN KEY (`id_reserva`)
    REFERENCES `cineflow`.`RESERVA` (`idReserva`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
